#pragma once

#define INIT_LED_SHOW_DURATION_MS 3000
#define INIT_WAIT_BEFORE_NEW_LED_MS 900
#define MIN_LED_SHOW_DURATION_MS 300
#define MAX_WAIT_BEFORE_NEW_LED_MS 5000

#define SCORE_NEEDED_TO_LEVEL_UP 10
#define SCORE_INCREMENT_PER_RIGHT_CLICK 2
#define SCORE_DECREMENT_PER_WRONG_CLICK 1
#define MAKE_HARDER_FACTOR 15

#define BLINK_DURATION_MS 200

